export const BAKERIES_LOADING = 'BAKERIES_LOADING';
export const ADD_BAKERIES = 'ADD_BAKERIES';
export const BAKERIES_FAILED = 'BAKERIES_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';